---
# Loads default set of integration's. Do not remove.
default_config:

# This Section is including basic configuration of the home assistant,
homeassistant:
  unit_system: metric
  # NOTE: Change here if the URL of the has System has changed.
  internal_url: http://server-albano.fritz.box:8123
  external_url: https://home.albano.xyz:443
  auth_providers:
    - type: homeassistant

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# The Zone is including information where my home is.
# Therefore this parameter is moved to an extra file, which will not checked in.
zone: !include zones.yaml

# Text to speech, use full for testing speakers
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

rest:
  #  Retrieving the remaining time of the timer from an adapter shelly plug.
  - scan_interval: 10
    resource: http://192.168.6.25/relay/0
    sensor:
      - name: "Kaffeemaschiene Timer"
        json_attributes_path: "$.response.timer_remaining"
        # The Value is delivered in seconds to display this in minutes a divided
        # the value by 60.
        value_template: "{{ value_json.timer_remaining| multiply(0.0166667) | round(0) }}"
        unique_id: kaffemaschiene_timer

  # Query pollen values for automatons from the German weather service.
  - scan_interval: 300
    resource: "https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json"
    sensor:
      - name: "Pollenflug Graser"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Graeser.today }}" 
      - name: "Pollenflug Ambrosia"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Ambrosia.today }}"
      - name: "Pollenflug Roggen"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Roggen.today }}"
      - name: "Pollenflug Beifuss"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Beifuss.today }}"
      - name: "Pollenflug Hasel"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Hasel.today }}"
      - name: "Pollenflug Erle"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Erle.today }}"
      - name: "Pollenflug Birke"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Birke.today }}"
      - name: "Pollenflug Esche"
        json_attributes_path: "$.response"
        value_template : "{{ value_json.content[3].Pollen.Esche.today }}"
