version: '2'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/has:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/external_disk:/mnt/external_disk/:ro
    restart: always
    privileged: true
    # Its recommend to use this network mode.
    # Generally speaking this network mode should be avoided, but some parts of
    # HAS are not working in other mode (e.g. Discovery for new devices).
    # Therefore I use this mode.
    network_mode: host
    mem_limit: 300m

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./data/mosquitto:/mosquitto/data
      - ./log/mosquitto:/mosquitto/log
    environment:
      - TZ=Europe/Berlin 
    mem_limit: 50m

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: always
    volumes:
      - ./data/zigbee:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8082:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_808098872780ef1189a7181cedd322a4-if00-port0:/dev/ttyACM0
